/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface KryptoDAOInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CreateProposal"
      | "GetProposal"
      | "VoteProposal"
      | "proposals"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "CreateProposal",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "GetProposal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VoteProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CreateProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GetProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VoteProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
}

export interface KryptoDAO extends BaseContract {
  connect(runner?: ContractRunner | null): KryptoDAO;
  waitForDeployment(): Promise<this>;

  interface: KryptoDAOInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CreateProposal: TypedContractMethod<
    [_name: string, _description: string],
    [void],
    "nonpayable"
  >;

  GetProposal: TypedContractMethod<
    [],
    [
      [string[], string[], bigint[], boolean[]] & {
        name: string[];
        description: string[];
        voteCount: bigint[];
        executed: boolean[];
      }
    ],
    "view"
  >;

  VoteProposal: TypedContractMethod<
    [proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  proposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        description: string;
        name: string;
        voteCount: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CreateProposal"
  ): TypedContractMethod<
    [_name: string, _description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "GetProposal"
  ): TypedContractMethod<
    [],
    [
      [string[], string[], bigint[], boolean[]] & {
        name: string[];
        description: string[];
        voteCount: bigint[];
        executed: boolean[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "VoteProposal"
  ): TypedContractMethod<[proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        description: string;
        name: string;
        voteCount: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  filters: {};
}
