/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as daoSol from "./dao.sol";
export type { daoSol };
export type { Counter } from "./Counter";
export * as factories from "./factories";
export { Counter__factory } from "./factories/Counter__factory";
export type { KryptoDAO } from "./dao.sol/KryptoDAO";
export { KryptoDAO__factory } from "./factories/dao.sol/KryptoDAO__factory";
